openapi: 3.0.3
info:
  title: Petstore API
  description: Comprehensive example with all HTTP methods
  version: 1.0.0
servers:
  - url: https://petstore.swagger.io/v2
paths:
  /pet:
    post:
      tags: [pet]
      summary: Add a new pet
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Pet'
      responses:
        '200':
          description: Successfully added pet
          
    put:
      tags: [pet]
      summary: Update existing pet
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Pet'
      responses:
        '200':
          description: Successfully updated pet

  /pet/{petId}:
    get:
      tags: [pet]
      summary: Get pet by ID
      parameters:
        - name: petId
          in: path
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Pet'
        '404':
          description: Pet not found
          
    delete:
      tags: [pet]
      summary: Delete a pet
      parameters:
        - name: petId
          in: path
          required: true
          schema:
            type: integer
      responses:
        '204':
          description: Successfully deleted

components:
  schemas:
    Pet:
      type: object
      required:
        - id
        - name
      properties:
        id:
          type: integer
          example: 1
        name:
          type: string
          example: "Buddy"
        status:
          type: string
          enum: [available, pending, sold]
  securitySchemes:
    api_key:
      type: apiKey
      name: api_key
      in: header